# Generated by Django 4.0.6 on 2022-07-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_products_description_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.producttypes')),
            ],
        ),
    ]
