# Generated by Django 4.0.6 on 2022-07-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productmenus'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmenus',
            name='application',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='shop.applicationname'),
        ),
    ]
