# Generated by Django 4.0.6 on 2022-08-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productmenus_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
