# Generated by Django 4.0.6 on 2022-08-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_size_products_density_products_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_init',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
