# Generated by Django 4.0.6 on 2022-09-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_products_price_init'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='density',
            new_name='character1',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='height',
            new_name='character2',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='length',
            new_name='character3',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='width',
            new_name='character4',
        ),
    ]
