# Generated by Django 4.0.6 on 2022-07-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_products_description_alter_products_image'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='cart_products',
        ),
        migrations.AddField(
            model_name='carts',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carts',
            name='cart_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.products'),
            preserve_default=False,
        ),
    ]
