# Generated by Django 4.0.6 on 2022-07-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productmenus'),
        ('cart', '0002_remove_carts_cart_products_carts_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='cart_product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='shop.products'),
        ),
    ]
