# Generated by Django 4.0.6 on 2022-07-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productmenus_application'),
        ('cart', '0003_alter_carts_cart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.applications')),
                ('cart_product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='shop.products')),
            ],
        ),
    ]
