# Generated by Django 4.0.6 on 2022-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_applications_applicationitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
